name: Build and Release

on:
  workflow_dispatch: # Allows manual trigger via GitHub UI

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet publish -c Release -r win-x64 --self-contained

      - name: Package app into zip
        run: |
          mkdir release
          # Copy the built files into the release folder
          copy /y .\bin\Release\net7.0\win-x64\publish\* .\release\
          # Zip the content
          Compress-Archive -Path .\release\* -DestinationPath .\release\app.zip

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release/app.zip
          asset_name: app.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
