name: Build and Test .NET Framework Project

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up NuGet
        uses: nuget/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore Broque\ Ramdisk.sln

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build solution
        run: msbuild Broque\ Ramdisk.sln /p:Configuration=Release

      - name: Test build output
        run: |
          if not exist "Broque Ramdisk/bin/Release/Broque Ramdisk.exe" (
            echo "Build output missing. Check logs for errors."
            exit 1
          )

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Broque-Ramdisk-Build
          path: Broque Ramdisk/bin/Release/
