name: Build Broque Ramdisk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Step 4: Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore "Broque Ramdisk.sln" --verbosity detailed

      # Step 5: Build the solution
      - name: Build solution
        run: msbuild "Broque Ramdisk.sln" /p:Configuration=Debug

      # Step 6: Archive build artifacts
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BroqueRamdiskBuild
          path: |
            Broque Ramdisk/bin/Debug/
