name: Build and Publish Release

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
    
    - name: Install Dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Publish application
      run: dotnet publish "Broque Ramdisk/Broque Ramdisk.csproj" -c Release -o ./out /p:PublishSingleFile=true /p:RuntimeIdentifier=win-x64 /p:SelfContained=true

    - name: Package the output
      run: |
        Compress-Archive -Path ./out/* -DestinationPath ./BroqueRamdisk.zip
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: BroqueRamdisk
        path: ./BroqueRamdisk.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: BroqueRamdisk

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tag || 'v1.0.0' }}
        release_name: Release ${{ github.event.inputs.tag || 'v1.0.0' }}
        draft: false
        prerelease: false

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./BroqueRamdisk.zip
        asset_name: BroqueRamdisk.zip
        asset_content_type: application/zip
